/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/cart': RouteRecordInfo<'/cart', '/cart', Record<never, never>, Record<never, never>>,
    '/fetchApi': RouteRecordInfo<'/fetchApi', '/fetchApi', Record<never, never>, Record<never, never>>,
    '/form': RouteRecordInfo<'/form', '/form', Record<never, never>, Record<never, never>>,
    '/pos/employee': RouteRecordInfo<'/pos/employee', '/pos/employee', Record<never, never>, Record<never, never>>,
    '/pos/main': RouteRecordInfo<'/pos/main', '/pos/main', Record<never, never>, Record<never, never>>,
    '/pos/productlist': RouteRecordInfo<'/pos/productlist', '/pos/productlist', Record<never, never>, Record<never, never>>,
    '/pos/stock': RouteRecordInfo<'/pos/stock', '/pos/stock', Record<never, never>, Record<never, never>>,
    '/pos-test': RouteRecordInfo<'/pos-test', '/pos-test', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
  }
}
